In [1]:
from sklearn import datasets
import pandas as pd
import numpy as np
bankNote = pd.read_csv('BankNoteAuthentication.csv')
bankNote

variance  skewness  curtosis  entropy  class
0      3.62160   8.66610   -2.8073 -0.44699      0
1      4.54590   8.16740   -2.4586 -1.46210      0
2      3.86600  -2.63830    1.9242  0.10645      0
3      3.45660   9.52280   -4.0112 -3.59440      0
4      0.32924  -4.45520    4.5718 -0.98880      0
...        ...       ...       ...      ...    ...
1367   0.40614   1.34920   -1.4501 -0.55949      1
1368  -1.38870  -4.87730    6.4774  0.34179      1
1369  -3.75030 -13.45860   17.5932 -2.77710      1
1370  -3.56370  -8.38270   12.3930 -1.28230      1
1371  -2.54190  -0.65804    2.6842  1.19520      1

[1372 rows x 5 columns]

In [2]:
bN = bankNote.rename(columns = {'class':'type'})

In [3]:
bN

variance  skewness  curtosis  entropy  type
0      3.62160   8.66610   -2.8073 -0.44699     0
1      4.54590   8.16740   -2.4586 -1.46210     0
2      3.86600  -2.63830    1.9242  0.10645     0
3      3.45660   9.52280   -4.0112 -3.59440     0
4      0.32924  -4.45520    4.5718 -0.98880     0
...        ...       ...       ...      ...   ...
1367   0.40614   1.34920   -1.4501 -0.55949     1
1368  -1.38870  -4.87730    6.4774  0.34179     1
1369  -3.75030 -13.45860   17.5932 -2.77710     1
1370  -3.56370  -8.38270   12.3930 -1.28230     1
1371  -2.54190  -0.65804    2.6842  1.19520     1

[1372 rows x 5 columns]

In [4]:
print(bN.type)

0       0
1       0
2       0
3       0
4       0
       ..
1367    1
1368    1
1369    1
1370    1
1371    1
Name: type, Length: 1372, dtype: int64


In [5]:
bN.isnull().sum()

variance    0
skewness    0
curtosis    0
entropy     0
type        0
dtype: int64

In [6]:
bN.type

0       0
1       0
2       0
3       0
4       0
       ..
1367    1
1368    1
1369    1
1370    1
1371    1
Name: type, Length: 1372, dtype: int64

In [7]:
from sklearn import preprocessing

type2 = bN['type']

# bN2 = bN why bN2 has different color

bN2 = bN.drop(['type'],axis='columns')




In [8]:
bN2

variance  skewness  curtosis  entropy
0      3.62160   8.66610   -2.8073 -0.44699
1      4.54590   8.16740   -2.4586 -1.46210
2      3.86600  -2.63830    1.9242  0.10645
3      3.45660   9.52280   -4.0112 -3.59440
4      0.32924  -4.45520    4.5718 -0.98880
...        ...       ...       ...      ...
1367   0.40614   1.34920   -1.4501 -0.55949
1368  -1.38870  -4.87730    6.4774  0.34179
1369  -3.75030 -13.45860   17.5932 -2.77710
1370  -3.56370  -8.38270   12.3930 -1.28230
1371  -2.54190  -0.65804    2.6842  1.19520

[1372 rows x 4 columns]

In [9]:
# Import train_test_split function
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
bN2_train, bN2_test, type2_train, type2_test = train_test_split(bN2, type2, test_size=0.3) # 70% training and 30% test

In [10]:
#Import knearest neighbors Classifier model
from sklearn.neighbors import KNeighborsClassifier

#Create KNN Classifier
knn = KNeighborsClassifier(n_neighbors=5)

#Train the model using the training sets
knn.fit(bN2_train, type2_train)

#Predict the response for test dataset
y_pred = knn.predict(bN2_test)

In [11]:
knn.score(bN2_test, type2_test)

1.0

In [12]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score
scores = cross_val_score(KNeighborsClassifier(n_neighbors=5), bN2, type2, cv=3)
np.average(scores)

1.0

In [13]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=6)
kf

KFold(n_splits=6, random_state=None, shuffle=False)

In [14]:
for train_index, test_index in kf.split([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]):
    print(train_index, test_index)

[ 2  3  4  5  6  7  8  9 10] [0 1]
[ 0  1  4  5  6  7  8  9 10] [2 3]
[ 0  1  2  3  6  7  8  9 10] [4 5]
[ 0  1  2  3  4  5  8  9 10] [6 7]
[ 0  1  2  3  4  5  6  7 10] [8 9]
[0 1 2 3 4 5 6 7 8 9] [10]


In [15]:
def get_score(model, bN2_train, bN2_test, type2_train, type2_test):
    model.fit(bN2_train, type2_train)
    return model.score(bN2_test, type2_test)

In [16]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_knn = []
bN2np = bN2.to_numpy()
ynp = type2.to_numpy()

for train_index, test_index in folds.split(bN2np,ynp):
    bN2_train, bN2_test, type2_train, type2_test = bN2np[train_index], bN2np[test_index], \
                                                            ynp[train_index], ynp[test_index]
    
    scores_knn.append(get_score(KNeighborsClassifier(n_neighbors=5), bN2_train, bN2_test, type2_train, type2_test))
np.average(scores)
   

1.0

In [17]:
bN2.feature_names

AttributeError: 'DataFrame' object has no attribute 'feature_names'